version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://malaria_user:1111@postgres:5432/malaria_db
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - ./backend/app/static:/app/app/static

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend

  postgres:
    image: postgres:14
    environment:
      - POSTGRES_DB=malaria_db
      - POSTGRES_USER=malaria_user
      - POSTGRES_PASSWORD=1111
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  